version: '3'
services:
  node:
    build: ./backend 
    ports:
      - '9000:9000'
    environment:
      DB_CONNECT: 'mongodb://root:rootpassword@mongodb:27017'
    depends_on:
      - mongodb
  react:
    build: ./frontend 
    ports:
      - '5173:5173'
    depends_on:
      - node
  mongodb:
    container_name: mongodb
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: Teamway
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container_teamway:/data/db
    #restart: always






volumes:
  mongodb_data_container_teamway: